spring:
  application:
    name: spring-webflux-docker-compose
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  docker:
    compose:
      lifecycle-management: start_and_stop
server:
  port: 8081
